# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host